### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by gitouche-sur-osm** [hauke96/simple-task-manager#121]
Hello,

I would like to contribute a french translation file.
Going into it, I have a few questions, based on **messages.de.xlf** : 

1) some `<target>` don't have the `xml:lang` and `state` attributes. cf. 
https://github.com/hauke96/simple-task-manager/blob/2d4907ff5447eb974b1907c8f77d9b8e6b2bb312/client/src/locale/messages.de.xlf#L902
Does the translation still works?

2) I need to write a lot of single quote characters in french. For example : _l'utilisateur_. Do I need to escape them (`&apos;`?) as to not interfere with `'<x ...>'` tags? cf. https://github.com/hauke96/simple-task-manager/blob/2d4907ff5447eb974b1907c8f77d9b8e6b2bb312/client/src/locale/messages.de.xlf#L670
Some other times, the `<x>` tags are not quoted at all : https://github.com/hauke96/simple-task-manager/blob/2d4907ff5447eb974b1907c8f77d9b8e6b2bb312/client/src/locale/messages.de.xlf#L822

Thanks

**Comment by hauke96** [comment]
Thanks for taking the effort of translating this project :)
As you'll see, I recommend to use the tool "Poedit" for translations, it's quite simple and straight forward. However I also sometimes manually write the entries.

There's also a (unfortunately short) description on internationalization in the [clients README](https://github.com/hauke96/simple-task-manager/tree/master/client#internationalization). If I find the time, I'll extend this description and also add some words on how to generally contribute to this project. However, here are the most important aspects:

1. Use the `dev` branch, because this is the code under active development. The translation files on `master` are probably outdated.
3. Always test your stuff before create a pull request ;) So at least run `npm run build-prod` in the `client` folder to see if there are any warnings/errors regarding your translations. There's one constant warning regarding the `zh-CN` translation but you can ignore that.
2. When I prepare a larger release (next larger release will be `1.3.0`), I always update the changelog on the login-page. So watch out for this, but it's no problem to make additional translation-only-releases after 1.3.0.

Regarding your questions:

1. The `xml:lang` and `state` tags are completely optional, the translation will work without them. Some translation tools will set them automatically, some don't set them. That is why some entries in the `.de` file have those tags and some don't. The tool Poedit for example sets both tags.

    I recommend to at least set the `state` because my `check-all.sh` script uses this state to check for equal entries whether they have been translated or not. E.g. the English entry "Name:" is equal to the German translation, here my script reads the `state` to determine if the German entry is the translation or if someone forgot to translate it.

2. The `'` will also appear in the text, so for example `The project '{{interp}}' has been removed` may result in `The project 'Foo' has been removed`. Therefore it's no problem to write `l'utilisateur` without `&apos;`. Poedit actually converts the `&apos;` occurrences into `'`.

If you have any questions or problems, don't hesitate to raise an issue :)
