### ISSUE TITLE
Shortcuts

### ISSUE THREAD

**Issue by hauke96** [hauke96/simple-task-manager#124]
Issue #123 by @ScriptForAll mentioned this: There are no shortcuts yet.

### Project creation
The following shortcuts were mentioned in the issue above:

* D : Start/end Draw mode
* SHIFT+D : Start/end deletetion mode
* E : Start/end edit mode

I like that but would add

* ESC : To end the current mode

### Project view
Maybe we find some useful shortcuts here as well?

* A : Assign yourself to a task
* U : Unassign yourself to a task
* D : Mark task as done
* J : Open JOSM
* I : Open iD

**Comment by ScriptForAll** [comment]
I suggest reserving each area of the keyboard for a set of (related) actions.
Since the "task management" actions have keys already close to each other I would use "A" for assigning tasks and "Shift+A" for unassigning. Instead of "D", you could use "C" to mark a task as done (as in "complete task").

With these keybiddings, all related tasks are close to each other, making easier to learn.

**Comment by hauke96** [comment]
I like the A / shift+A idea but I would stick to D to mark a task as **d**one because it's easier to remember (like J to open **J**OSM). I understand that the function behind the D key depends on the are you are currently in, but that's pretty normal behavior in my opinion.
