### ISSUE TITLE
JOSM: Download data based on task geometry

### ISSUE THREAD

**Issue by westnordost** [hauke96/simple-task-manager#155]
So STM supports importing task boundaries from geojson/overpass queries, which is a great feature!
![image](https://user-images.githubusercontent.com/4661658/124355161-154eb800-dc10-11eb-999b-f8d8313bae7b.png)

However, when pressing open in JOSM button, I only get the boundary and need to download myself. This is not that helpful, because
- the boundary is not well visible while editing in JOSM - it's in another layer, it is just grey...
- I can only download rectangles, so I have to download a log of rectangles to cover the area I want to cover for the task. Sometimes/often hitting the "download area too big!" limit

What would be great if STM automatically calculated the max bounding box for a task and supplied a URL to download exactly this data from. Maybe this could work easily with
https://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#By_polygon_.28poly.29

**Comment by hauke96** [comment]
Unfortunately JOSM doesn't offer the possibility to specify a Overpass-query when calling via remote-control URL. A hack-around would be to generate an overpass-URL (like ` https://overpass-api.de/api/interpreter?data=%5Bout%3Ajson%5D%5Btimeout%3A25%5D%3B%0A........`) and pass this over to JOSM like this: `127.0.0.1:8111/import?url=https://overpass-api.de/api/interpreter?data=.......`. This a) works as far as I just tried manually and b) is even mentioned in a discussion in the JOSM issue tracker, so it's nearly an official solution :smile: 

It's maybe even possible to only download the data within the geometry of the task, so that only the data needed is downloaded.

**Comment by westnordost** [comment]
> It's maybe even possible to only download the data within the geometry of the task, so that only the data needed is downloaded.

Yeah, that is what I am suggesting

**Comment by hauke96** [comment]
I just deployed a new snapshot version on https://stm-test.hauke-stieler.de where this issue should be implemented. It would be great if you test it a bit to see if it works as expected.

**Comment by westnordost** [comment]
I tested it with the "Stammtisch Project", it works! Though, the tasks in the Stammtisch projects only consists of squares anyway, so can't say if it works correctly with any polygon

**Comment by hauke96** [comment]
Thank, I also tested it a couple of times and it works pretty good so far.
