### ISSUE TITLE
Feature request: Support custom JOSM commands per task

### ISSUE THREAD

**Issue by DavidKarlas** [hauke96/simple-task-manager#160]
What I would like to do as part of import project is to call JOSM `GET /import?url=https://MyAwesomeDataToBeImported.com/task25.osm`.

The way this feature should probably be implemented is to not make any UI changes to keep it simple, but only when importing GeoJson look for specific property on feature named "josm_commands"(to allow multiple layers imports) or something like that and call that when JOSM editor is used by user.

**Comment by hauke96** [comment]
Thanks for the feature request, however I don't quite get it. As far as I understand, you described the following scenario:

1. You create a project locally with your favorite GIS software (JOSM, QGIS, whatever). You add the property `josm_commands=foobar` to your polygons.
2. You import the polygons into STM
3. You open a task in JOSM
4. Because of the `josm_commands=foobar` property on each task, STM now calls JOSM via `GET /import?url=...` instead of the currently used `GET /load_data?data=...`

Did I understood that correctly so far?

If I understood the above correctly, then my question is: Why do you want to use the `/import` API of JOSM instead of the `/load_data` one? Whenever I open a task in JOSM, a new layer will be created, that's why I don't see any difference here.

**Comment by DavidKarlas** [comment]
First of all, thank you for awesome project... I never worked with Go or Typescript, so don't laugh at my changes 😄 
I set up my own instance of STM at https://osm.karlas.si/

I hacked it so on signup/login I add new user to project that I host there see [HACK](https://github.com/DavidKarlas/simple-task-manager/commit/aa49075997736994fb2cd7dfc18dadf72b13ea87#diff-75f47054f1e19878c7fc67f7c50cbf2ad5f3ed4dfade83c666fa9b0b5a474696R178-R181), when I thought a bit more about it, it might make sense to add `bool IsPublic` column to projects table and when new user is logged in add it to all projects with `IsPublic=true`, and tada, https://github.com/hauke96/simple-task-manager/issues/49 is fixed :)

Then I added "fix" for https://github.com/hauke96/simple-task-manager/issues/139 where I propagate and respect `maxProcessPoints`.

And last thing I made Feature as imported into project also stay same, so no more `new Feature(feature.getGeometry())`. Which allowed for `josmCommands` to be accessible at ["Open in JOSM"](https://github.com/DavidKarlas/simple-task-manager/commit/aa49075997736994fb2cd7dfc18dadf72b13ea87#diff-1499b6bcf6094c1b286c7319dbd3ed51e76eb046b906231386f4a09c18c377ffR111) time.

Here is example of how my projectImport.json looks like, this is generated by my tool:
https://gist.github.com/DavidKarlas/771de05326522e96c07fb138a8a15095

Reason I want to load my custom layers is, that as I said this is import project, so one of layers is meant to be merged into OSM Data layer, any issues that happen with merged fixed and then uploaded, hence this feature request.

**Comment by hauke96** [comment]
Thanks for elaborating this, I think I know what this is about. However I don't have the feeling that this feature is something for STM as it's
* very implicit or this feature needs larger UI adjustments so that the users can define the commands when creating a project within STM
* quite technical (a lot of OSM users barely know what GeoJson is for example)
* probably only applies to very few users

So sorry, but for now this feature doesn't fit into STM.

Apart from the feature request, I have to say something regarding the public projects: There's a reason why it hasn't been implemented yet and I e.g. talked with Frederik Ramm and some others about this .
The HOT tasking manager has public projects and the local community somethines struggles with the changes made by HOT users. For example: Someone works on a task on Uganda with the suggested Bing imagery but that imagery is quite blurry and old. Local mappers have to do a lot of work to fix your mistakes due to the bad imagery this person used. Also a lot of people are not accurately working on the tasks, meaning the resulting data quality is sometimes quite bad or wrong data is added. As those people are not part of the project, because it's public, they don't really care about the project, data quality etc.
There's no good solution to prevent this kind of harmful behavour of many mappers (even if they act in good faith). This is why I haven't implemented this feature.
