### ISSUE TITLE
[question] how to remove assigned tasks?

### ISSUE THREAD

**Issue by govvin** [hauke96/simple-task-manager#199]
I couldn't seem to find the option to un-assign or change assignment of a task?

**Comment by hauke96** [comment]
Hi, so there are three situations:

1) You're alone in a project: There's no assign/unassign at all. You can freely work on any task because you're alone.

![image](https://github.com/hauke96/simple-task-manager/assets/9700906/60cb5204-49e3-4953-aedc-7b814644d89b)

2) You're working with others on a project. If you're assigned to a task and select that task, then you can unassign yourself.

![image](https://github.com/hauke96/simple-task-manager/assets/9700906/46b31aa8-6ae1-465e-a446-c6f04f809a48)

3) You're working with others on a project. If you select a task where some other user is assigned to, then you cannot unassign that user. Only that other user can unassign himself. 

![image](https://github.com/hauke96/simple-task-manager/assets/9700906/59d95ff8-27fe-47ca-9b7f-52467b7c04d5)


I hope that helps. If you have any other problems, please let me know with some information (project ID, screenshots, etc.).

**Comment by govvin** [comment]
Yes, I suspect that that's the workflow. Thank you.

So, if a user assigns a task(s) to themselves, and become inactive without completing it, other users won't be able to complete them. (Well, at least STM will not report it as completed.)

Do task assignments expire? For example if the task is assigned for some time duration (1 day? 3 days? a week?), whether or not edits are being made (which STM doesn't monitor), it reverts to unassigned.

If the user wants to continue working on a task, they can simply re-assign themselves to it. If the user becomes inactive, other people can still complete the task. Maybe the time setting is for the whole project itself?

**Comment by hauke96** [comment]
In summary yes, an inactive but assigned user stays assigned forever.

But: You (as an owner) can remove that user from the project, which unassignes that user from all tasks. When you re-add that user, it's like a reset on all tasks.

I would rather not implement an automatic unassignment. It's more complex than a simple unassign button.

I think an "unassign"-button, that is always visible for the owner of a project, would be a good idea. I added the issue #201 , feel free to add a reaction, comment, question, etc. on that issue.

**Comment by hauke96** [comment]
The corresponding issue #201 is in doing, I therefore close this question-issue. Feel free to re-open it if you have further questions regarding this topic or to start a new issue.
